eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka
logging:
    level:
        org:
            springframework:
                cloud:
                    gateway: TRACE
                    gateway.handler: TRACE
                    loadbalancer: DEBUG
                web:
                    reactive:
                        function:
                            client:
                                ExchangeFunctions: TRACE
server:
    port: 8888
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            httpclient:
                wiretap: true
            routes:
                - id: identity-service-route
                  uri: lb://IDENTITY-SERVICE
                  predicates:
                      - Path=/identity/**